// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxSbBmnQL6rcCMaNb5K4c4bxX91vRX8lk',
    appId: '1:802843071359:web:8c94542877fc8927c0404a',
    messagingSenderId: '802843071359',
    projectId: 'ceritasakuapi',
    authDomain: 'ceritasakuapi.firebaseapp.com',
    databaseURL: 'https://ceritasakuapi-default-rtdb.firebaseio.com',
    storageBucket: 'ceritasakuapi.appspot.com',
    measurementId: 'G-GJ9JCNX5HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-pTJ6ZbxdlIrBCwSp72GYh5DQlwSZck',
    appId: '1:802843071359:android:0d21af7f868b0f7ac0404a',
    messagingSenderId: '802843071359',
    projectId: 'ceritasakuapi',
    databaseURL: 'https://ceritasakuapi-default-rtdb.firebaseio.com',
    storageBucket: 'ceritasakuapi.appspot.com',
  );
}
